name:                botcleanr
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/rksm/botcleanr#readme
license:             BSD3
author:              Robert Krahn
maintainer:          robert@kra.hn
copyright:           2018 Robert Krahn
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - hspec


executables:
  botcleanr:
    source-dirs:      src
    main:             Main.hs

library:
  source-dirs:      src
  exposed-modules:
    - Botcleanr

tests:
  botcleanr-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - botcleanr
